# Categories
## categories: ['main', 'sub']
### main cat (main folder)
    + test [for test and sandbox]       
    + image [[for all image related processing]]
    + economy
### sub cat (sub folder)
    + processing [image]
    + indices

# Tags (other notes)
+ Test [for test and sandbox]
+ Image [for all image related processing]
+ Html [for .html pages]
+ MD [for .md pages]
+ Econ [for all economy related] 